services:
  app:
    command: >
      sh -c "python -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5679 -m
      uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 &
      watchmedo shell-command --patterns='*.py' --recursive --command='pytest' /usr/src/app"
    ports:
      - "5679:5679"
# services:
#   app:
#     command: >
#       sh -c "
#       python -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5679 -m
#       uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 &
#       watchmedo shell-command --patterns='*.py' --recursive --command='pytest' /usr/src/app &
#       while true; do touch /usr/src/app/touchfile.py; sleep 60; done
#       "
#     ports:
#       - "5679:5679"
